import type { Metadata } from "next";
import Head from "next/head";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import Image from "next/image";

// Styles
import "boxicons/css/boxicons.min.css";

// Components
import UserProfileButton from "@/components/LayoutComponents/UserProfileButton";

// Clerk
import {
  ClerkProvider,
  UserButton,
  SignInButton,
  SignUpButton,
  SignedOut,
  SignedIn
} from "@clerk/nextjs";

import { auth } from "@clerk/nextjs/server";
import prisma from "@/lib/prisma";
import { NextResponse } from "next/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>

) {

  async function getUserId() {
    const { userId } = await auth()
    
    const user = await prisma.user.findUnique({
      where: {clerkId: String(userId)}
    })

    if (!user) {
      return NextResponse.json({ message: `Cannot find user on by clerkId: ${userId}`}, { status: 401 })
    }
    return user
  }

  const user = getUserId();

  return (
    <ClerkProvider>
      <html lang="en">

        <body className={`${inter.className} antialiased`}>
          <Navbar actingUser={user}/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

const Navbar = (actingUser: any) => {

  return (
    <div></div>
  );
};