import type { Metadata } from "next";
// import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import Link from "next/link";

// Styles
import "boxicons/css/boxicons.min.css";

// Components
import UserProfileButton from "@/components/LayoutComponents/UserProfileButton";
import Footer from "@/components/LayoutComponents/Footer";

// Clerk
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedOut,
  SignedIn,
} from "@clerk/nextjs";

import { auth } from "@clerk/nextjs/server";

import prisma from "@/lib/prisma";
import { User } from "@prisma/client";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function getUser() {
    const { userId } = await auth();

    if (!userId) {
      return null;
    }

    if (!userId) {
      return null;
    }

    const user = await prisma.user.findUnique({
      where: { clerkId: String(userId) },
    });

    if (!user) {
      throw new Error(`User not found for ID: ${userId}`);
    }
    return user;
  }

  const user = await getUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <Navbar actingUser={user} />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

const Navbar = ({ actingUser }: { actingUser: User | null }) => {
  return (
    <div className="w-full shadow bg-background sticky top-0 z-50">
      <input
        type="checkbox"
        id="menu-toggle"
        className="peer hidden md:hidden"
      />
      {/* Mode Desktop & Tablet */}
      <header className="container mx-auto hidden md:flex items-center justify-between h-16 px-4">
        {/* LEFT: LOGO + MENU */}
        <div className="flex items-center gap-10">
          <a href="/" className="flex items-center gap-2">
            <img
              src="/logos/logo-white.png"
              alt="Bisma Informatika"
              className="h-8 w-auto"
            />
          </a>

          <nav>
            <ul className="flex items-center gap-8">
              <li>
                <a href="/" className="font-medium hover:underline">
                  Home
                </a>
              </li>
              <li>
                <a href="/courses" className="font-medium hover:underline">
                  Courses
                </a>
              </li>
              <li>
                <a href="/about" className="font-medium hover:underline">
                  About
                </a>
              </li>
              <li>
                <a href="/contact" className="font-medium hover:underline">
                  Contact Us
                </a>
              </li>
            </ul>
          </nav>
        </div>

        {/* Right Auth*/}
        <div className="flex items-center gap-3">
          <a href="/login" className="font-medium hover:underline">
            Login
          </a>
          <span className="text-gray-400">|</span>
          <a href="/register" className="font-medium hover:underline">
            Register
          </a>
        </div>
      </header>

      {/* Mobile Header */}
      <header className="container mx-auto flex md:hidden items-center justify-between h-16 px-4">
        {/* Logo */}
        <a href="/">
          <img
            src="/logos/logo-white.png"
            alt="Bisma Informatika"
            className="h-8 w-auto"
          />
        </a>

        {/* Hamburger */}
        <label
          htmlFor="menu-toggle"
          className="cursor-pointer flex flex-col gap-1 mr-2
          transition-transform duration-200 active:scale-95"
        >
          <span className="block w-6 h-0.5 bg-black transition-all duration-300"></span>
          <span className="block w-6 h-0.5 bg-black transition-all duration-300"></span>
          <span className="block w-6 h-0.5 bg-black transition-all duration-300"></span>
        </label>
      </header>

      {/* Mobile Menu Animation*/}
      <div
        className="md:hidden
        max-h-0 opacity-0 -translate-y-2
        overflow-hidden
        transition-all duration-300 ease-out
        peer-checked:max-h-[500px]
        peer-checked:opacity-100
        peer-checked:translate-y-0
        bg-background px-6"
      >
        <ul className="flex flex-col gap-4 py-4">
          <li>
            <a href="/" className="text-lg">
              Home
            </a>
          </li>
          <li>
            <a href="/courses" className="text-lg">
              Courses
            </a>
          </li>
          <li>
            <a href="/about" className="text-lg">
              About
            </a>
          </li>
          <li>
            <a href="/contact" className="text-lg">
              Contact Us
            </a>
          </li>
        </ul>

        <div className="pb-4">
          <a href="/login" className="block py-2 text-lg hover:underline">
            Login
          </a>
          <a href="/register" className="block py-2 text-lg hover:underline">
            Register
          </a>
        </div>
      </div>
    </div>
  );
};
